Reducing pytest output by dfault and storing the debug output to a
wise-agents/wise-agents pull request #269
Opened 2024-09-10 12:16 UTC by ehsavoie

pytest.log file.

2024-09-10 16:07 UTC, kabir commented
@ehsavoie will this still output to the console on CI? File output is a bit painful there.

This is the command on CI: https://github.com/wise-agents/wise-agents/blob/main/.github/workflows/build-and-test-workflow-run.yml#L115

````
pytest --log-cli-level=DEBUG -m "not needsllm and not needsllama"
````

2024-09-11 12:11 UTC, ehsavoie commented
@kabir you can still override it with the cli parameter. I set it to CRITICAL but maybe INFO would be best

2024-09-13 09:37 UTC, maeste requested changes

2024-09-13 09:37 UTC, maeste commented on pyproject.toml
> +log_cli_level = "CRITICAL"
I think INFO is more appropriate

2024-09-13 09:38 UTC, maeste commented on pyproject.toml
> +log_cli_level = "CRITICAL"
Hmm, maybe not... let's give it a try. Approving and merging it as is

2024-09-13 09:39 UTC, maeste approved these changes

2024-09-13 09:39 UTC, merged